version: "3"
services:
  python-app:
    restart: always
    build: .
    container_name: "python-app"
    working_dir: "/root/"
    tty: true
    volumes:
      - ./src:/root/src
    ports:
      - 8000:8000
